--PART 3: DATA ANALYSIS
--NAME : DRASHTI KAKADIYA(25414741)

USE DATABASE STARBUCKS_DB;
USE SCHEMA STARBUCKS_SCHEMA;

-- PART 4A - BEST OFFER AS PER AGE GROUP SO I THING THIS IS BEST IDEA TO GIVE OFEER ACCORDING TO AGE SO COUNT NUMBER OF CUSTOMERS WHO RECIEVED AND INTERACTED.

--MOST CUSTOMERS PARTICIPATING = MOST POPULAR OFFER AGE GROUP

--STEP1:- TAKE ALL OFFER RELATED EVENT FROM TRANSCRIPT_EXT
WITH STAR_EVENT_BASE AS (
    SELECT
        VALUE:"person"::STRING AS PERSON_ID,
        VALUE:"event"::STRING  AS EVENT_NAME,
        COALESCE(
            VALUE:"value"."offer id"::STRING,
            VALUE:"value"."offer_id"::STRING
        ) AS OFFER_ID
    FROM TRANSCRIPT_EXT
    WHERE VALUE:"event"::STRING IN (
        'offer received',
        'offer viewed',
        'offer completed'
    )
),

-- STEP 2: ATTACH AGE_GROUP TO THE EVENT
STAR_EVENT_WITH_AGE AS (
    SELECT
        a.AGE_GROUP,
        a.ID           AS PERSON_ID,
        b.OFFER_ID,
        b.EVENT_NAME
    FROM PROFILE a
    JOIN STAR_EVENT_BASE b
      ON a.ID = b.PERSON_ID
),

--STEP 3:- COUNT DIFFRENT CUSTOMER INTERACTED WITH EACH OFFER INSIDE AGE GROUP
STAR_AGE_OFFER_CUSTOMERS AS (
    SELECT
        AGE_GROUP,
        OFFER_ID,
        COUNT(DISTINCT PERSON_ID) AS STAR_NUM_CUSTOMERS_INTERACTED
    FROM STAR_EVENT_WITH_AGE
    GROUP BY AGE_GROUP, OFFER_ID
),

--STEP 4:- WE BRING ALL OFFER DETAILS LIKE DIFFICULTY, REWARD AND DURATION ETC.
STAR_AGE_OFFER_DETAIL AS (
    SELECT
        a.AGE_GROUP,
        a.OFFER_ID,
        a.STAR_NUM_CUSTOMERS_INTERACTED,
        b.OFFER_TYPE,
        b.DIFFICULTY,
        b.REWARD,
        b.DURATION
    FROM STAR_AGE_OFFER_CUSTOMERS a
    LEFT JOIN PORTFOLIO b
      ON a.OFFER_ID = b.ID
),

--STEP 5:- MOST CUSTOMER AND REWARD THAT OFFERS INSIDE EACH AGE GROUP 
STAR_AGE_BEST_OFFER AS (
    SELECT
        a.*,
        ROW_NUMBER() OVER (
            PARTITION BY AGE_GROUP
            ORDER BY STAR_NUM_CUSTOMERS_INTERACTED DESC,
                     REWARD DESC
        ) AS STAR_RANK_IN_GROUP
    FROM STAR_AGE_OFFER_DETAIL a
)

--STEP 6:- ONE OF THE BEST OFFER PER AGE GROUP ACCORDING MY IDEA
SELECT
    AGE_GROUP,
    OFFER_ID,
    OFFER_TYPE,
    DIFFICULTY,
    DURATION,
    REWARD                      AS STAR_OFFER_REWARD,
    STAR_NUM_CUSTOMERS_INTERACTED,
    STAR_RANK_IN_GROUP
FROM STAR_AGE_BEST_OFFER
WHERE STAR_RANK_IN_GROUP = 1
ORDER BY AGE_GROUP;

--PART 4B – COMPAIGN COST
--IN OUR SECOND BUSINESS QUE TO DO THIS IDEAS SO I WILL PUT ALL STEPS BELOW:-
--      1. CUSTOMER COUNT IN EACH AGE GROUP
--      2. MAIN SIMPLE CTE QUERY USE
--      3. COST BY AGE GROUP
--      4. TOTAL COST FOR STARBUCKS LIKE  75%, 50% AND 25% CUSTOMER COMPLETE THE OFFER 
  
--STEP 1:- CUSTOMER COUNT IN EACH AGE GROUP
SELECT
    CASE
        WHEN AGE = 118 THEN 'UNKNOWN'                  --TOTAL CUSTOMER COUNT = 2175
        WHEN AGE < 20 THEN 'TEENAGERS'                 --TOTAL CUSTOMER COUNT = 205
        WHEN AGE >= 20 AND AGE < 30 THEN '20S'         --TOTAL CUSTOMER COUNT = 1369  
        WHEN AGE >= 30 AND AGE < 40 THEN '30S'         --TOTAL CUSTOMER COUNT = 1526
        WHEN AGE >= 40 AND AGE < 50 THEN '40S'         --TOTAL CUSTOMER COUNT = 2309
        WHEN AGE >= 50 AND AGE < 60 THEN '50S'         --TOTAL CUSTOMER COUNT = 3541
        ELSE '60S'
    END AS AGE_GROUP,
    COUNT(DISTINCT ID) AS TOTAL_CUSTOMERS
FROM PROFILE
GROUP BY 1
ORDER BY 1;

-- STEP 2:- SIMPLE STAR CAMPAIGN COST BY AGE GROUP

WITH STAR_CAMPAIGN AS (
    -- AGE_GROUP, TOTAL_CUSTOMERS (from Step 1), REWARD_UNITS (from PORTFOLIO)

    SELECT '20S'      AS AGE_GROUP, 1369 AS TOTAL_CUSTOMERS,  5 AS REWARD_UNITS  UNION ALL
    SELECT '30S'      AS AGE_GROUP, 1526 AS TOTAL_CUSTOMERS, 10 AS REWARD_UNITS  UNION ALL
    SELECT '40S'      AS AGE_GROUP, 2309 AS TOTAL_CUSTOMERS,  8 AS REWARD_UNITS  UNION ALL
    SELECT '50S'      AS AGE_GROUP, 3541 AS TOTAL_CUSTOMERS,  5 AS REWARD_UNITS  UNION ALL
    SELECT '60S'      AS AGE_GROUP, 5875 AS TOTAL_CUSTOMERS,  3 AS REWARD_UNITS  UNION ALL
    SELECT 'TEENAGERS' AS AGE_GROUP,  205 AS TOTAL_CUSTOMERS,  4 AS REWARD_UNITS UNION ALL
    SELECT 'UNKNOWN'   AS AGE_GROUP, 2175 AS TOTAL_CUSTOMERS,  6 AS REWARD_UNITS
)

-- STEP 3:- CALCULATE COST FOR EACH AGE GROUP
SELECT
    AGE_GROUP,
    TOTAL_CUSTOMERS,
    REWARD_UNITS,
    TOTAL_CUSTOMERS * REWARD_UNITS * 0.75 AS COST_75_PERCENT,
    TOTAL_CUSTOMERS * REWARD_UNITS * 0.50 AS COST_50_PERCENT,
    TOTAL_CUSTOMERS * REWARD_UNITS * 0.25 AS COST_25_PERCENT
FROM STAR_CAMPAIGN
ORDER BY AGE_GROUP;

-- STEP 4: TOTAL CAMPAIGN COST
WITH STAR_CAMPAIGN AS (
    SELECT '20S'       AS AGE_GROUP, 1369 AS TOTAL_CUSTOMERS, 5 AS REWARD_UNITS UNION ALL
    SELECT '30S'       AS AGE_GROUP, 1526 AS TOTAL_CUSTOMERS,10 AS REWARD_UNITS UNION ALL
    SELECT '40S'       AS AGE_GROUP, 2309 AS TOTAL_CUSTOMERS, 8 AS REWARD_UNITS UNION ALL
    SELECT '50S'       AS AGE_GROUP, 3541 AS TOTAL_CUSTOMERS, 5 AS REWARD_UNITS UNION ALL
    SELECT '60S'       AS AGE_GROUP, 5875 AS TOTAL_CUSTOMERS, 3 AS REWARD_UNITS UNION ALL
    SELECT 'TEENAGERS' AS AGE_GROUP,  205 AS TOTAL_CUSTOMERS, 4 AS REWARD_UNITS UNION ALL
    SELECT 'UNKNOWN'   AS AGE_GROUP, 2175 AS TOTAL_CUSTOMERS, 6 AS REWARD_UNITS
)

SELECT
    SUM(TOTAL_CUSTOMERS * REWARD_UNITS * 0.75) AS STAR_COST_75,    --67332.75
    SUM(TOTAL_CUSTOMERS * REWARD_UNITS * 0.50) AS STAR_COST_50,    --44888.5
    SUM(TOTAL_CUSTOMERS * REWARD_UNITS * 0.25) AS STAR_COST_25     --22444.25
FROM STAR_CAMPAIGN;

--END OF PART D
--THANK YOU

