--PART 2: DATA CLEANING/ TRANFORMATION
--NAME : DRASHTI KAKADIYA(25414741)

USE DATABASE STARBUCKS_DB;
USE SCHEMA STARBUCKS_SCHEMA;
--A. REPLACE NULL VALUES GENTER TO "O" AND INCOME TO 0 IN PROFILE TABLE

--A. GENDER WITH "O"
UPDATE PROFILE
SET GENDER = CASE
   WHEN GENDER IS NULL THEN 'O'
   ELSE GENDER
  END; 
--RESULT TO SHOWING 'O'
select*
from profile;

--B. INCOME WITH 0
UPDATE profile
SET INCOME = CASE
   WHEN INCOME IS NULL THEN '0'
   ELSE INCOME
  END; 

--SHOWING TO NULL REPLACE TO 0
SELECT * FROM PROFILE;

--DOUBLE CHECK IS IT WOKING TO 0 IN TABLE
SELECT DISTINCT INCOME
FROM PROFILE 
ORDER BY INCOME;

--B.CREATE NEW COLUMN AGE_GROUP AND CHANGE SOME AGE IN PROFILE TABLE 
ALTER TABLE PROFILE
ADD COLUMN AGE_GROUP VARCHAR;

UPDATE PROFILE
SET AGE_GROUP = 
CASE
  WHEN AGE= 118 THEN 'UNKNOWN'
  WHEN AGE < 20 THEN 'TEENAGERS'
  WHEN AGE >= 20 AND AGE <30 THEN '20s'
  WHEN AGE >= 30 AND AGE <40 THEN '30s'
  WHEN AGE >= 40 AND AGE <50 THEN '40s'
  WHEN AGE >= 50 AND AGE <60 THEN '50s'
  WHEN AGE >=60 THEN '60s'
END;

--SHOWING RESULT TO AGE_GROUP
SELECT AGE_GROUP FROM PROFILE;

--C. ADD 4 DIFFRENT COULMN IN CHANNELS
ALTER TABLE PORTFOLIO
ADD COLUMN CHANNEL_EMAIL BOOLEAN,
           CHANNEL_MOBILE BOOLEAN,
           CHANNEL_SOCIAL BOOLEAN,
           CHANNEL_WEB BOOLEAN;

UPDATE PORTFOLIO
SET
 CHANNEL_EMAIL = (channels like '%email%'
 ),
 CHANNEL_MOBILE = (channels like '%mobile%'
 ),
 CHANNEL_SOCIAL = (channels like '%social%'
 ) ,
 CHANNEL_WEB = (channels like '%web%'
 ) ;

-- D. Create combined table with no duplicate ID columns
CREATE OR REPLACE TABLE starbucks_full AS
SELECT
    p.id AS person_id,
    p.age,
    p.gender,
    p.income,
    p.age_group,
    p.became_member_on,

    t.event,
    t.time,
    t.offerid,

    f.channels,
    f.difficulty,
    f.duration,
    f.reward,
    f.offer_type

FROM transcript t
LEFT JOIN profile p
    ON t.person = p.id
LEFT JOIN portfolio f
    ON t.offerid = f.id;

SHOW TABLES LIKE 'STARBUCKS_FULL';

--E. NUMBER OF ROWS IN STARBUCKS_FULL
SELECT COUNT(*) FROM STARBUCKS_FULL;    --306534

--F. REMOVE THE INFORMATIONAL IN STARBUCKS_FULL
DELETE FROM STARBUCKS_FULL
WHERE OFFER_TYPE = 'informational';     --26066

--showing result
SELECT DISTINCT OFFER_TYPE
FROM STARBUCKS_FULL;

--G. AFTER REMOVING ALL DATA AND FINAL ROW COUNT IS 280468
SELECT COUNT(*) FROM STARBUCKS_FULL;        

--END OF PART B
--THANK YOU 