--PART 3: DATA ANALYSIS
--NAME : DRASHTI KAKADIYA(25414741)

USE DATABASE STARBUCKS_DB;
USE SCHEMA STARBUCKS_SCHEMA;

--A.TOP 5 CLIENT BASED ON TOTAL DOLLAR SPEND,TRANSACTIONS AND ALSO AVERAGE AMOUNT PER TRANSACTION
SELECT VALUE
FROM TRANSCRIPT_EXT
WHERE value:event::string = 'transaction'
LIMIT 5;

WITH T AS (
    SELECT
        VALUE:"person"::STRING        AS PERSON_ID,
        VALUE:"value"."amount"::FLOAT AS AMOUNT
    FROM TRANSCRIPT_EXT
    WHERE VALUE:"event"::STRING = 'transaction'
      AND VALUE:"value"."amount" IS NOT NULL
)
SELECT PERSON_ID,
       COUNT(*)      AS STAR_NUM_TRANSACTIONS,
       SUM(AMOUNT)   AS STAR_TOTAL_SPEND,
       AVG(AMOUNT)   AS STAR_AVG_AMOUNT_PER_TRANSACTIONS
FROM T
GROUP BY PERSON_ID
ORDER BY STAR_TOTAL_SPEND DESC
LIMIT 5;


--B.AGE GROUP METRICS QUERY
--PART 1: PREPARE CUSTOMER & EVENT TABLES 
WITH STAR_CUSTOMER AS (
    SELECT DISTINCT
        ID AS PERSON_ID,   
        AGE_GROUP,
        COALESCE(TRY_TO_NUMBER(INCOME::STRING), 0) AS INCOME_NUM
    FROM PROFILE
),

--CLEAN ALL THE CONVERT VARIANT VALUES INTO USABLE NUMBERS
STAR_EVENT AS (
    SELECT
        VALUE:"person"::STRING AS PERSON_ID,
        VALUE:"event"::STRING  AS EVENT_NAME,

        --AMOUNT TO NUMERIC
        COALESCE(TRY_TO_NUMBER(VALUE:"value"."amount"::STRING), 0) AS AMOUNT_SPENT,

        --REWARD TO NUMERIC
        COALESCE(TRY_TO_NUMBER(VALUE:"value"."reward"::STRING), 0) AS EVENT_REWARD,

        --OFFER_ID TO TWO DIFFRENT THINGS
        COALESCE(
            VALUE:"value"."offer id"::STRING,
            VALUE:"value"."offer_id"::STRING
        ) AS OFFER_ID
    FROM TRANSCRIPT_EXT
),

--JOINNING ATTACH DIFFICULTY IN PORTFOLIO TABLE
STAR_EVENT_WITH_DIFF AS (
    SELECT
        a.PERSON_ID,
        a.EVENT_NAME,
        a.AMOUNT_SPENT,
        a.EVENT_REWARD,
        a.OFFER_ID,
        TRY_TO_NUMBER(b.DIFFICULTY::STRING) AS DIFFICULTY_NUM
    FROM STAR_EVENT a
    LEFT JOIN PORTFOLIO b    
           ON a.OFFER_ID = b.ID
),

--PART 2: CUSTOMER-LEVEL AGGREGATION
--ALL TRANSACTION COUNTS, TOTAL SPENT, REWARDS, DIFFICULTY

--COUNT TRANSACTION, OFFERS AND MONEY SPENT TO CUSTOMER
STAR_EVENT_AGG AS (
    SELECT
        PERSON_ID,
        COUNT_IF(EVENT_NAME = 'transaction')      AS NUM_TRANSACTIONS,
        COUNT_IF(EVENT_NAME = 'offer received')   AS NUM_OFFERS_RECEIVED,
        COUNT_IF(EVENT_NAME = 'offer completed')  AS NUM_OFFERS_COMPLETED,

        SUM(CASE WHEN EVENT_NAME = 'transaction' THEN AMOUNT_SPENT ELSE 0 END)
            AS TOTAL_SPENT,

        SUM(CASE WHEN EVENT_NAME = 'offer completed' THEN EVENT_REWARD ELSE 0 END)
            AS TOTAL_REWARD_EARNED
    FROM STAR_EVENT_WITH_DIFF
    GROUP BY PERSON_ID
),

--CALCULATE AVERAGE DIFFICULTY COMPLETED OFFER PER COSTOMER
STAR_DIFF_AGG AS (
    SELECT
        PERSON_ID,
        AVG(DIFFICULTY_NUM) AS AVG_COMPLETED_DIFFICULTY
    FROM STAR_EVENT_WITH_DIFF
    WHERE EVENT_NAME = 'offer completed'
      AND DIFFICULTY_NUM IS NOT NULL
    GROUP BY PERSON_ID
),

--SHOW ALL THE METRIC LINE THAT WE WANT USING ONLY a,b,c aliases 
STAR_CUSTOMER_SUMMARY AS (
    SELECT
        a.PERSON_ID,
        a.AGE_GROUP,
        a.INCOME_NUM,

        COALESCE(b.NUM_TRANSACTIONS, 0)        AS STAR_NUM_TRANSACTIONS,
        COALESCE(b.NUM_OFFERS_RECEIVED, 0)     AS STAR_NUM_OFFERS_RECEIVED,
        COALESCE(b.NUM_OFFERS_COMPLETED, 0)    AS STAR_NUM_OFFERS_COMPLETED,
        COALESCE(b.TOTAL_SPENT, 0)             AS STAR_TOTAL_SPENT,
        COALESCE(b.TOTAL_REWARD_EARNED, 0)     AS STAR_TOTAL_REWARD_EARNED,
        COALESCE(c.AVG_COMPLETED_DIFFICULTY,0) AS STAR_AVG_COMPLETED_DIFFICULTY
    FROM STAR_CUSTOMER a          -- alias "a"
    LEFT JOIN STAR_EVENT_AGG b    -- alias "b"
           ON a.PERSON_ID = b.PERSON_ID
    LEFT JOIN STAR_DIFF_AGG c     -- alias "c"
           ON a.PERSON_ID = c.PERSON_ID
)

--PART 3: FINAL METRICS BY AGE GROUP
SELECT
    AGE_GROUP,

    COUNT(*) AS STAR_NUM_CUSTOMER,
    AVG(INCOME_NUM) AS STAR_AVG_INCOME,

    SUM(STAR_TOTAL_SPENT) AS STAR_TOTAL_AMOUNT_SPENT,
    SUM(STAR_NUM_TRANSACTIONS) AS STAR_TOTAL_TRANSACTIONS,
    SUM(STAR_NUM_OFFERS_RECEIVED) AS STAR_TOTAL_OFFERS_RECEIVED,
    SUM(STAR_NUM_OFFERS_COMPLETED) AS STAR_TOTAL_OFFERS_COMPLETED,
    SUM(STAR_TOTAL_REWARD_EARNED) AS STAR_TOTAL_REWARD_EARNED,

    AVG(STAR_TOTAL_SPENT) AS STAR_AVG_SPENT_PER_CUSTOMER,

    CASE
        WHEN SUM(STAR_NUM_TRANSACTIONS) = 0 THEN 0
        ELSE SUM(STAR_TOTAL_SPENT) / SUM(STAR_NUM_TRANSACTIONS)
    END AS STAR_AVG_SPENT_PER_TRANSACTION,

    AVG(STAR_NUM_OFFERS_RECEIVED) AS STAR_AVG_OFFERS_PER_CUSTOMER,
    AVG(STAR_NUM_OFFERS_COMPLETED) AS STAR_AVG_COMPLETED_OFFERS_PER_CUSTOMER,

    AVG(STAR_TOTAL_REWARD_EARNED) AS STAR_AVG_REWARD_PER_CUSTOMER,
    AVG(STAR_AVG_COMPLETED_DIFFICULTY) AS STAR_AVG_DIFFICULTY_COMPLETED_PER_CUSTOMER,

    COUNT_IF(STAR_NUM_TRANSACTIONS >= 3) AS STAR_ACTIVE_CUSTOMERS

FROM STAR_CUSTOMER_SUMMARY
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP;

--END OF PART C
--THANK YOU